# Generated by Django 5.0.14 on 2026-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
            options={
                'db_table': 'localities',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=60, null=True, unique=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
