# Generated by Django 5.0.14 on 2026-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_locality_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
