# Generated by Django 5.0.14 on 2026-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(db_table='artist_type', related_name='artists', to='reservations.type'),
        ),
    ]
