# Generated by Django 5.0.14 on 2026-08-24 20:56

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    admin_group, _ = Group.objects.get_or_create(name='ADMIN')
    admin_group.permissions.set(Permission.objects.all())

    member_group, _ = Group.objects.get_or_create(name='MEMBER')
    member_group.permissions.set(Permission.objects.filter(codename__startswith='view_'))


def delete_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['ADMIN', 'MEMBER']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_usermeta'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_default_groups),
    ]
