# Generated by Django 5.0.14 on 2026-08-24 21:13

from django.db import migrations


def resync_admin_group_permissions(apps, schema_editor):
    """
    La migration 0007 a attribué toutes les permissions existantes au groupe
    ADMIN à ce moment-là. Comme les permissions d'un modèle ne sont créées
    (par le signal post_migrate) qu'une fois la migration qui crée ce modèle
    appliquée, les modèles ajoutés plus tard (Show, Representation, Review, ...)
    n'ont pas été inclus automatiquement. On resynchronise donc le groupe ADMIN
    avec l'ensemble des permissions actuelles.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    admin_group = Group.objects.filter(name='ADMIN').first()
    if admin_group:
        admin_group.permissions.set(Permission.objects.all())

    member_group = Group.objects.filter(name='MEMBER').first()
    if member_group:
        member_group.permissions.set(Permission.objects.filter(codename__startswith='view_'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_representation_review'),
    ]

    operations = [
        migrations.RunPython(resync_admin_group_permissions, noop),
    ]
