# Generated by Django 5.0.14 on 2026-08-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_resync_admin_group_permissions'),
    ]

    operations = [
        # IMPORTANT : on supprime d'abord l'ancienne ManyToManyField (et sa table
        # artist_type) AVANT de créer le modèle pivot ArtistType, qui réutilise
        # le même nom de table db_table='artist_type'. Si on créait le nouveau
        # modèle avant de supprimer l'ancien champ, la migration échouerait avec
        # "table artist_type already exists" (erreur rencontrée en générant
        # cette migration avec makemigrations, qui ordonne les opérations par
        # ordre alphabétique de modèle et non par dépendance logique).
        migrations.RemoveField(
            model_name='artist',
            name='types',
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname'), name='unique_firstname_lastname'),
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'artist_type',
            },
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'artist_type_show',
            },
        ),
        migrations.AddField(
            model_name='artisttype',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='a_artistTypes', to='reservations.artist'),
        ),
        migrations.AddField(
            model_name='artisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='t_artistTypes', to='reservations.type'),
        ),
        migrations.AddField(
            model_name='artisttypeshow',
            name='artist_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistTypeShows', to='reservations.artisttype'),
        ),
        migrations.AddField(
            model_name='artisttypeshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistTypeShows', to='reservations.show'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_types',
            field=models.ManyToManyField(related_name='shows', through='reservations.ArtistTypeShow', to='reservations.artisttype'),
        ),
        migrations.AlterUniqueTogether(
            name='artisttypeshow',
            unique_together={('show', 'artist_type')},
        ),
    ]
