# Generated by Django 5.0.14 on 2026-08-27 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='affiliate_tier',
            field=models.CharField(choices=[('none', 'Aucun (non affilié)'), ('free', 'Free'), ('starter', 'Starter'), ('premium', 'Premium')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='press_articles', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='press_articles', to='reservations.show')),
            ],
            options={
                'db_table': 'press_articles',
            },
        ),
    ]
