# Generated by Django 5.0.14 on 2026-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_resync_admin_permissions_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressarticle',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
